### ISSUE TITLE
how to import new js module from node_modules 

### ISSUE THREAD

**Issue by githubgobi** [ninhva/html-boilerplate#4]

**Comment by ninhva** [comment]
You can see my example:

Styles: [https://github.com/ninhva/html-boilerplate/blob/master/src/views/layouts/styles.html](https://github.com/ninhva/html-boilerplate/blob/master/src/views/layouts/styles.html)

Scripts: [https://github.com/ninhva/html-boilerplate/blob/master/src/views/layouts/scripts.html](https://github.com/ninhva/html-boilerplate/blob/master/src/views/layouts/scripts.html)

**Comment by githubgobi** [comment]
thanks
